### ISSUE TITLE
引入第三方依赖各种冲突报错

### ISSUE THREAD

**Issue by ariwori** [halo-sigs/halo-plugin-template#33]

**Comment by ariwori** [comment]
插件开发获取用户信息文档不全

**Comment by guqing** [comment]
文档问题建议到 halo-dev/docs 提交 issue，至于你说的引入第三方依赖报错，建议提供日志，以及引入的是什么依赖，目前无法复现

**Comment by ariwori** [comment]
https://github.com/Wechat-Group/WxJava
引入这个的企业微信开发，一写相关逻辑就会报错

**Comment by guqing** [comment]
> [Wechat-Group/WxJava](https://github.com/Wechat-Group/WxJava) 引入这个的企业微信开发，一写相关逻辑就会报错

建议提供复现步骤以及详细的日志，而不是这样笼统的描述，我怎么复现呢

**Comment by ariwori** [comment]
暂时放弃这个依赖了，自己实现功能了，不理它先
想问一下怎么样在插件理做免登录验证的接口

**Comment by guqing** [comment]
> 暂时放弃这个依赖了，自己实现功能了，不理它先 想问一下怎么样在插件理做免登录验证的接口

参考文档 [聚合角色](https://docs.halo.run/developer-guide/plugin/api-reference/server/role-template#%E8%81%9A%E5%90%88%E8%A7%92%E8%89%B2:~:text=%E5%A6%82%E6%9E%9C%E4%BD%A0%E6%83%B3%E5%B0%86%E4%BD%A0%E5%86%99%E7%9A%84%E8%B5%84%E6%BA%90%E5%9E%8B%20APIs%20%E5%85%AC%E5%BC%80%E7%BB%99%E6%89%80%E6%9C%89%E7%94%A8%E6%88%B7%E8%AE%BF%E9%97%AE)
通过定义角色模板并聚合到 anonymous 角色上实现免登陆

**Comment by ariwori** [comment]
好的，谢谢

**Comment by ariwori** [comment]
![image](https://github.com/halo-dev/plugin-starter/assets/39097573/f054bb1d-07b6-4aeb-ae39-153dfc10f584)
![image](https://github.com/halo-dev/plugin-starter/assets/39097573/cdaf1690-c72d-464f-87db-9fa2515d9392)
请问我这样写有什么问题吗，接口还是401

**Comment by guqing** [comment]
角色模板的 rules 配置错了，参考文档：[API 权限控制](https://docs.halo.run/developer-guide/plugin/api-reference/server/role-template#:~:text=%E4%BB%A5%E4%B8%8A%E5%AE%9A%E4%B9%89%E8%A7%92%E8%89%B2%E6%A8%A1%E6%9D%BF%E7%9A%84%E6%96%B9%E5%BC%8F%E9%80%82%E5%90%88%E8%B5%84%E6%BA%90%E5%9E%8B%E8%AF%B7%E6%B1%82%EF%BC%8C%E5%8D%B3%E9%9C%80%E8%A6%81%E7%AC%A6%E5%90%88%E4%BB%A5%E4%B8%8B%E8%A7%84%E5%88%99)
角色模板的 rules 中的 apiGroups,resources 根据路由规则来套 `/apis/<apiGroup>/<version>/<resource>[/<resourceName>/<subresource>]`
因此按照你定义的路由，app 是 resource,reveiveMsg 是 resourceName

**Comment by ariwori** [comment]
![image](https://github.com/halo-dev/plugin-starter/assets/39097573/6b91ea2b-ffa6-44c2-8f8c-2309b9aa356e)
![image](https://github.com/halo-dev/plugin-starter/assets/39097573/93bf70c2-9cee-418d-a84f-46ca75b8029f)
POST请求成功了，GET请求还是401
![image](https://github.com/halo-dev/plugin-starter/assets/39097573/736e4a68-e2f9-4548-8359-6cf3337cea26)
![image](https://github.com/halo-dev/plugin-starter/assets/39097573/8707e55d-36ad-4f5d-a233-47194e95b5d2)

**Comment by guqing** [comment]
试试
```yaml
apiVersion: v1alpha1
kind: Role
metadata:
  name: qywx-role
  labels:
    halo.run/role-template: "true"
    rbac.authorization.halo.run/aggregate-to-anonymous: "true"
rules:
  # 以 apis 开头的 API 是资源型 URL，需要指定 apiGroups 和 resources
  - apiGroups: [ "wqlin.halo.run" ]
    resources: [ "app" ]
    resourceNames: [ "receiveMsg" ]
    verbs: [ "get" ]
  # 这个 URL 虽然以 /apis 开头，但是路径中有 resourceName 段，创建时通过不可能在路径中包含 resourceName，所以是非资源型 URL
  - nonResourceURLs: [ "/apis/wqlin.halo.run/v1alpha1/app/receiveMsg" ]
    verbs: [ "create" ]
```
需要注意的是，开发插件时建议使用自己的域名作为 group，不要使用 halo.run，为了根据规则定义合适的 API，你可以选择这样定义
`/apis/api.your-domain.com/v1alpha1/apps/-/receiveMsg`即通过`-`来代替名称，将 action 放到后面一段
